CREATE TABLE accounts(
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'Primary Key',
  name VARCHAR(255),
  email VARCHAR(255),
  picture VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT charset utf8 COMMENT '';
-- DROP TABLE accounts;
CREATE Table keeps(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: creatorId',
  name VARCHAR(255),
  description VARCHAR(255),
  tag VARCHAR(255),
  img VARCHAR(255),
  views int,
  shares int,
  keeps int,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
) DEFAULT charset utf8 COMMENT '';
-- DROP TABLE keeps;
SELECT
  *
FROM
  keeps CREATE TABLE vaults(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    creatorId VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    description VARCHAR(255),
    isPrivate TINYINT DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
  ) DEFAULT charset utf8 COMMENT '';
--  DROP TABLE vaults;
  CREATE TABLE vault_keeps(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    creatorId VARCHAR(255) NOT NULL,
    vaultId int NOT NULL,
    keepId int NOT NULL,
    FOREIGN KEY (vaultId) REFERENCES vaults(id) ON DELETE CASCADE,
    FOREIGN KEY (keepId) REFERENCES keeps(id) ON DELETE CASCADE,
    FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
  ) DEFAULT charset utf8 COMMENT '';
-- DROP TABLE vault_keeps;